config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    # no need for app/views/restaurants/create.html.erb
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="titulo text-center" >Edit Article!</h1>
  <div class="form-group">
      <%= form_for(@article) do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= f.label :title %>
        <%= f.text_field :title,class:"form-control" %>
        <%= f.label :content %>
        <%= f.text_area :content,class:"form-control mb-4" %>
        <%= f.submit class:"btn btn-dark"  %>
      <% end %>
      <%= link_to "GO BACK", articles_path, class:"btn btn-dark mt-3" %>
    </div>
</div>

app/views/articles/index.html.erb
<div class="container text-center mt-4">
  <ul>
  <% @articles.each do |article|%>
  <li class = "listasinpunto">
  <%= link_to "#{article[:title]}", article_path(article.id) %>
    <p><%= "#{article[:content]}" %> </p>
  </li >
  <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="titulo text-center">New Article!</h1>
  <div class="form-group">
    <%= form_for(@article) do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.label :title %>
      <%= f.text_field :title,class:"form-control" %>
      <%= f.label :content %>
      <%= f.text_area :content,class:"form-control mb-4" %>
      <%= f.submit class:"btn btn-dark"  %>
    <% end %>
    <%= link_to "GO BACK", articles_path, class:"btn btn-dark mt-3" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container text-center">
  <h3 class="tarea text-center p-2"><%= @article.title %></h4>
  <h5><%= @article.content %></h5>
  <%= link_to "GO BACK", articles_path, class: "btn btn-dark" %>
  <%= link_to "EDIT", edit_article_path, class: "btn btn-dark" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-dark bg-dark">
    <%= link_to "Wiki Benja and Seba", articles_path, class: "navbar-brand benjseb" %>
    <form class="form-inline">
      <%= link_to "Create New Article", new_article_path, class: "btn btn-outline-light my-2 my-sm-0" %>
    </form>
  </nav>

    <%= yield %>
  </body>
</html>